a = input('Digite algo: ')
print('O tipo primitivo desse valor é:', type(a))
print('Só tem espacos?', a.isspace())
print('Só tem número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está em maiúsculas?', a.isupper())
print('Está em minúsculas?', a.islower())
print('Está capitalizada?',a.istitle())
#Programa que você digita algo, ele mostra o tipo primitivo do que foi digitado e depois verifica o que foi digitado.
